language: cpp
compiler:
- g++
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
- sudo add-apt-repository -y ppa:george-edison55/precise-backports
- sudo add-apt-repository -y ppa:boost-latest/ppa
- sudo apt-get update -qq
install:
- sudo apt-get install -y ninja-build
- sudo apt-get install -y gcc-4.8 g++-4.8
- sudo apt-get install -y cmake=3.2.3-5ppa5~precise1 cmake-data=3.2.3-5ppa5~precise1
- sudo apt-get install -y qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5gui5
- sudo apt-get install -y libboost1.55-dev
- sudo sed -i -e 's/COPY_ONLY/COPYONLY/g' /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreMacros.cmake
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
before_script:
- cmake . -G "Ninja"
script:
- ninja
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    rooms:
      - horizonlauncher:VBY2bmPSmg4UbzvE6ZCVODQJ#general
      - horizonlauncher:VBY2bmPSmg4UbzvE6ZCVODQJ#client
os:
- linux
